### ISSUE TITLE
Concert gazebo workflow diagram

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/concert_services#29]
I'd like this diagram to show what is going on with a concert gazebo launch. Store it in the concert gazebo package.

It will be useful for documentation later.

**Comment by jihoonl** [comment]
![configuration](https://docs.google.com/drawings/d/1Kq2ycJhI9N9DRO-FMbhAOTM9Kisj2YwHaO8WFZmqHN8/pub?w=960&h=720)

Example files:
- [turtlebot.concert_gazebo](https://github.com/robotics-in-concert/concert_services/blob/indigo/concert_service_gazebo/robots/turtlebot/turtlebot.concert_gazebo)
- [package.xml in concert_service_gazebo](https://github.com/robotics-in-concert/concert_services/blob/indigo/concert_service_gazebo/package.xml)
- [gazebo_robot_world.parameters](https://github.com/robotics-in-concert/concert_services/blob/indigo/concert_service_gazebo/services/gazebo_robot_world/gazebo_robot_world.parameters)

**Comment by jihoonl** [comment]
![workflow](https://docs.google.com/drawings/d/1Q6xMlu0pfQAj0rJFxojjEg0DJUINTUHKZtgNOWb-Y9o/pub?w=957&h=719)

example files:
- [concert_service_gazebo service](https://github.com/robotics-in-concert/concert_services/blob/indigo/concert_service_gazebo/services/gazebo_robot_world/gazebo_robot_world.service)
- [robot.launch](https://github.com/robotics-in-concert/concert_services/blob/indigo/concert_service_gazebo/launch/robot.launch)
- [turtlebot spawner](https://github.com/robotics-in-concert/concert_services/blob/indigo/concert_service_gazebo/robots/turtlebot/turtlebot.launch)
- [turtlebot_rapps/video_teleop](https://github.com/turtlebot/turtlebot_apps/blob/indigo/turtlebot_rapps/rapps/video_teleop/video_teleop.launch)

**Comment by jihoonl** [comment]
Ah store with package. got it.

**Comment by stonier** [comment]
Leaving this open - need to polish it and put it inside some sphinx docs, along with motivation (why we flip out) we have this design.
