### ISSUE TITLE
Timeout as service parameter for teleop service

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/concert_services#3]
the current teleop_pimp is hard-coded to use for turtlesim in `teleop_pimp.py`

resource and timeout should be configuration to use for other platform like turtlebot.

See example in 

https://github.com/robotics-in-concert/rocon_services/tree/turtlebot_teleop

**Comment by stonier** [comment]
Could you paste code here so I don't have to go trawling?

**Comment by jihoonl** [comment]
I had to reconfigure Resource and Timeout to use `concert_teleop_app` with a real Turtlebot.

Resources : 
https://github.com/robotics-in-concert/rocon_services/blob/turtlebot_teleop/rocon_service_teleop/scripts/teleop_pimp.py#L101
https://github.com/robotics-in-concert/rocon_services/blob/turtlebot_teleop/rocon_service_teleop/scripts/teleop_pimp.py#L141

Timeout:
https://github.com/robotics-in-concert/rocon_services/blob/turtlebot_teleop/rocon_service_teleop/scripts/teleop_pimp.py#L146
https://github.com/robotics-in-concert/rocon_services/blob/turtlebot_teleop/rocon_service_teleop/scripts/teleop_pimp.py#L82

**Comment by stonier** [comment]
The resource name is awaiting updates with ancestor app specifications. When they go in, this service will update to match.

Maybe timeouts should be a customisable service parameter? Do you want to tackle this?

**Comment by stonier** [comment]
Service parameterisation added in pull request #5.

@jihoonl - reference issues from your commits, then they will close automagically.
