### ISSUE TITLE
Gazebo robots without flips

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/concert_services#33]
Can we possibly move the spawning of gazebo robots to the client ros masters instead of having to spawn them in the concert master and flip?

Current issue is that all spawnings of ros plugins seem to require a gazebo ros namespace (from `gazebo_ros/spawn_model`):

```
-gazebo_namespace <gazebo ros_namespace> - optional: ROS namespace of gazebo offered ROS interfaces.  Defaults to /gazebo/ (e.g. /gazebo/spawn_model).
```

What if we just flip this gazebo ros namespace to each spawned terminal and call the spawn_model script from inside there?

**Comment by stonier** [comment]
@jihoonl has a point here though, even if you spawn from the ros master on the other side (i.e. inside the rocon launched terminal), then it will still contact gazebo ros, who is the one responsible for `ros_init` and of course, it has initialised with the concert master details. Consequently any robot plugin's topics will go to the concert master, not its own master.

See [gazebo ros docs](http://www.google.com/url?q=http%3A%2F%2Fwww.gazebosim.org%2Ftutorials%3Ftut%3Dros_plugins%26cat%3Dconnect_ros%23RunthePlugin&sa=D&sntz=1&usg=AFQjCNE_vbXTa6k_8mLEwRj4FD0z7sq_Xw) for more details.

If we wanted to do this without those flips, we'd need to write our own wrapper around gazebo that would handle the ros initialisation differently (not even sure if it would be possible to do that).

**Comment by stonier** [comment]
And possibly, not worth the maintainance of a `gazebo_rocon`.

**Comment by jihoonl** [comment]
Please reopen if necessary.
